default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gluscription_development

test:
  <<: *default
  database: gluscription_test

production:
  <<: *default
  database: gluscription_production
